language: java

jdk:
  - openjdk11
  - openjdk8

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner

addons:
  sonarcloud:
    organization: "fortnoxab"
